# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(411, 496)
        font = QtGui.QFont()
        font.setFamily("SimSong")
        MainWindow.setFont(font)
        self.SingerPlayer = QtWidgets.QPushButton(MainWindow)
        self.SingerPlayer.setEnabled(True)
        self.SingerPlayer.setGeometry(QtCore.QRect(50, 250, 311, 51))
        font = QtGui.QFont()
        font.setFamily("FZQingKeBenYueSongS-R-GB")
        self.SingerPlayer.setFont(font)
        self.SingerPlayer.setStyleSheet("border-radius:10px;\n"
"border:2px solid #252121;\n"
"background-color:#464242;\n"
"color:#CFFEAE;")
        self.SingerPlayer.setCheckable(False)
        self.SingerPlayer.setObjectName("SingerPlayer")
        self.AI = QtWidgets.QPushButton(MainWindow)
        self.AI.setGeometry(QtCore.QRect(50, 350, 311, 51))
        font = QtGui.QFont()
        font.setFamily("FZQingKeBenYueSongS-R-GB")
        self.AI.setFont(font)
        self.AI.setStyleSheet("border-radius:10px;\n"
"border:2px solid #252121;\n"
"background-color:#464242;\n"
"color:#CFFEAE;")
        self.AI.setObjectName("AI")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(90, 100, 251, 81))
        font = QtGui.QFont()
        font.setFamily("FZQingKeBenYueSongS-R-GB")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.RuleButton = QtWidgets.QPushButton(MainWindow)
        self.RuleButton.setGeometry(QtCore.QRect(20, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("FZQingKeBenYueSongS-R-GB")
        font.setPointSize(14)
        self.RuleButton.setFont(font)
        self.RuleButton.setStyleSheet("border-radius:10px;\n"
"border:2px solid #252121;\n"
"background-color:#464242;\n"
"color:#CFFEAE;")
        self.RuleButton.setObjectName("RuleButton")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "警察抓小偷"))
        self.SingerPlayer.setText(_translate("MainWindow", "单机游戏"))
        self.AI.setText(_translate("MainWindow", "人机对战"))
        self.label.setText(_translate("MainWindow", "警察抓小偷"))
        self.RuleButton.setText(_translate("MainWindow", "?"))
