# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rule.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Rule(object):
    def setupUi(self, Rule):
        Rule.setObjectName("Rule")
        Rule.resize(569, 380)
        self.pushButton = QtWidgets.QPushButton(Rule)
        self.pushButton.setGeometry(QtCore.QRect(410, 330, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Rule)
        self.label.setGeometry(QtCore.QRect(20, 100, 531, 211))
        font = QtGui.QFont()
        font.setFamily("FZFangSong-Z02S")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Rule)
        self.label_2.setGeometry(QtCore.QRect(90, 0, 391, 101))
        font = QtGui.QFont()
        font.setFamily("FZFangSong-Z02S")
        font.setPointSize(48)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Rule)
        QtCore.QMetaObject.connectSlotsByName(Rule)

    def retranslateUi(self, Rule):
        _translate = QtCore.QCoreApplication.translate
        Rule.setWindowTitle(_translate("Rule", "规则"))
        self.pushButton.setText(_translate("Rule", "知道了"))
        self.label.setText(_translate("Rule", "游戏分为两个阵营：警察阵营和小偷阵营。小偷的任务是：寻找宝藏并且带离出口，而警察则需要抓住小偷，阻止他偷东西。游戏的地图是由点和线组成的，每个点之间有线连接，可以通过这些线到达另一个点。接下来是几个特殊的点：绿色：出口；天蓝：宝藏；蓝灰：小偷出生点；粉红：警察出生点；橙色：小偷目前所在位置；紫色：警察目前所在位置。游戏先由小偷开始，其次是警察，每人每回合只能走一步（从一个点到另一个点）由鼠标控制。当前回合的角色会高亮显示。线也有特殊的路线：橙色：小偷专用路线；紫色：警察专用路线。顾名思义，小偷专用路线和警察专用路线只能是小偷或警察才能走"))
        self.label_2.setText(_translate("Rule", "警察抓小偷-规则"))
